/**
 * Re-exports the canonical contract ABIs from `packages/contracts/abis/v1.0/`,
 * regenerated by `pnpm --filter @klaro/contracts sync-abis` (also wired into
 * `pnpm --filter @klaro/contracts build`).
 * the previous arrangement let hand-rolled ABI
 * slices in `arcClient.ts` and `abi.ts` drift from the deployed contracts.
 * The hand-rolled slices stay (viem needs `as const` literal tuples for type
 * inference), but every slice is now drift-checked here via `assertSliceMatchesCanonical`:
 * a missing function or a changed input/output tuple throws at module load.
 * Pipeline: edit .sol → forge build → sync-abis writes JSON → web reloads → assert runs.
 */
import invoiceEscrowArtifact from "../../../packages/contracts/abis/v1.0/InvoiceEscrow.json";
import auditReceiptArtifact from "../../../packages/contracts/abis/v1.0/AuditReceipt.json";

type AbiEntry = {
  type: string;
  name?: string;
  stateMutability?: string;
  inputs?: readonly {
    name?: string;
    type: string;
    components?: readonly unknown[];
  }[];
  outputs?: readonly {
    name?: string;
    type: string;
    components?: readonly unknown[];
  }[];
};

export const CANONICAL_INVOICE_ESCROW_ABI =
  invoiceEscrowArtifact.abi as readonly AbiEntry[];
export const CANONICAL_AUDIT_RECEIPT_ABI =
  auditReceiptArtifact.abi as readonly AbiEntry[];

/**
 * Assert that a hand-rolled ABI slice (each entry keyed by `type:name`)
 * exists verbatim in the canonical ABI. Compares input + output tuple shapes
 * including nested components — the exact drift class P0-4 hit.
 * Normalizes `internalType` + omitted-name (forge emits `"name":""` on
 * unnamed return positions) before compare, since neither affects the
 * wire-level ABI shape that viem cares about.
 */
type NormParam = { name: string; type: string; components?: NormParam[] };
function normalizeParams(
  params:
    | readonly {
        name?: string;
        type: string;
        components?: readonly unknown[];
      }[]
    | undefined,
): NormParam[] {
  return (params ?? []).map((p) => ({
    name: p.name ?? "",
    type: p.type,
    ...(p.components
      ? { components: normalizeParams(p.components as never) }
      : {}),
  }));
}

export function assertSliceMatchesCanonical(
  contractName: string,
  slice: readonly AbiEntry[],
  canonical: readonly AbiEntry[],
): void {
  for (const want of slice) {
    if (!want.name) continue;
    const got = canonical.find(
      (c) => c.type === want.type && c.name === want.name,
    );
    if (!got) {
      throw new Error(
        `[abiCanonical] ${contractName}.${want.name} (${want.type}) missing from ` +
          `packages/contracts/abis/v1.0/${contractName}.json — run \`pnpm --filter ` +
          `@klaro/contracts sync-abis\` after rebuilding contracts.`,
      );
    }
    const wantSig =
      JSON.stringify(normalizeParams(want.inputs)) +
      "→" +
      JSON.stringify(normalizeParams(want.outputs));
    const gotSig =
      JSON.stringify(normalizeParams(got.inputs)) +
      "→" +
      JSON.stringify(normalizeParams(got.outputs));
    if (wantSig !== gotSig) {
      throw new Error(
        `[abiCanonical] ${contractName}.${want.name} signature drift.\n` +
          `  slice:     ${wantSig}\n  canonical: ${gotSig}\n` +
          `Update the hand-rolled slice to match the regenerated JSON.`,
      );
    }
  }
}
