/**
 * Daemon-side ABI drift guard. Mirrors apps/web/lib/abiCanonical.ts.
 *
 * Every hand-rolled `parseAbiItem("event Foo(...)")` literal in
 * arcSubscriber.ts must agree with the canonical event in the matching
 * `packages/contracts/abis/v1.0/<Contract>.json` (regenerated by
 * `pnpm --filter @klaro/contracts sync-abis`). When the contract
 * changes its event shape and someone forgets to update the literal,
 * viem derives a topic the chain never emits — listener silently
 * matches zero events with `listener.started: true` health checks.
 * This module asserts the canonical-vs-literal match at daemon boot
 * so the mismatch throws instead of producing a silent zero-traffic
 * daemon (the exact failure mode QA-027/030/031/032/041 each repeated).
 */
import invoiceEscrowArtifact from "../../../../packages/contracts/abis/v1.0/InvoiceEscrow.json";
import auditReceiptArtifact from "../../../../packages/contracts/abis/v1.0/AuditReceipt.json";
import cashoutOrderProcessorArtifact from "../../../../packages/contracts/abis/v1.0/CashoutOrderProcessor.json";
import disputeManagerArtifact from "../../../../packages/contracts/abis/v1.0/DisputeManager.json";
import agentEscrowArtifact from "../../../../packages/contracts/abis/v1.0/AgentEscrow.json";

type AbiEntry = {
  type: string;
  name?: string;
  inputs?: readonly { name?: string; type: string; indexed?: boolean }[];
};

const REGISTRY: Record<string, readonly AbiEntry[]> = {
  InvoiceEscrow: invoiceEscrowArtifact.abi as readonly AbiEntry[],
  AuditReceipt: auditReceiptArtifact.abi as readonly AbiEntry[],
  CashoutOrderProcessor:
    cashoutOrderProcessorArtifact.abi as readonly AbiEntry[],
  DisputeManager: disputeManagerArtifact.abi as readonly AbiEntry[],
  AgentEscrow: agentEscrowArtifact.abi as readonly AbiEntry[],
};

function sig(e: AbiEntry): string {
  if (e.type !== "event" || !e.name) return "";
  const params = (e.inputs ?? [])
    .map((i) => `${i.indexed ? "indexed " : ""}${i.type}`)
    .join(",");
  return `${e.name}(${params})`;
}

/**
 * Each entry: the listener's hand-rolled event sig + which canonical
 * contract it should match. Order: stable.
 */
const EVENT_BINDINGS: { contract: string; literal: string }[] = [
  {
    contract: "InvoiceEscrow",
    literal:
      "InvoicePaid(indexed bytes32,indexed address,uint256)",
  },
  {
    contract: "InvoiceEscrow",
    literal:
      "InvoiceSettled(indexed bytes32,indexed address,uint256)",
  },
  {
    contract: "InvoiceEscrow",
    literal:
      "InvoiceRefunded(indexed bytes32,indexed address,uint256)",
  },
  {
    contract: "CashoutOrderProcessor",
    literal: "OrderClaimed(indexed bytes32,indexed bytes32)",
  },
  {
    contract: "CashoutOrderProcessor",
    literal:
      "ProofSubmittedFor(indexed bytes32,indexed bytes32)",
  },
  {
    contract: "CashoutOrderProcessor",
    literal:
      "OrderReleased(indexed bytes32,indexed bytes32,uint256)",
  },
  {
    contract: "DisputeManager",
    literal:
      "CaseOpened(indexed bytes32,indexed address,indexed address,bytes32,bytes32)",
  },
  {
    contract: "DisputeManager",
    literal:
      "Decided(indexed bytes32,uint8,indexed bytes32,bytes32)",
  },
  {
    contract: "AgentEscrow",
    literal: "JobCompleted(indexed bytes32,uint256,uint256)",
  },
  {
    contract: "AuditReceipt",
    literal:
      "ReceiptMinted(indexed uint256,indexed bytes32,indexed bytes32,address)",
  },
];

export function assertListenerEventSigs(): void {
  for (const { contract, literal } of EVENT_BINDINGS) {
    const canonical = REGISTRY[contract];
    if (!canonical) {
      throw new Error(
        `[abiAssert] no canonical artifact loaded for ${contract}`,
      );
    }
    const found = canonical.some((e) => sig(e) === literal);
    if (!found) {
      const eventName = literal.split("(")[0];
      const candidates = canonical
        .filter((e) => e.type === "event" && e.name === eventName)
        .map(sig);
      throw new Error(
        `[abiAssert] daemon listener event ${literal} not found in ` +
          `packages/contracts/abis/v1.0/${contract}.json. ` +
          `Canonical candidates for ${eventName}: ${
            candidates.length ? candidates.join(" | ") : "(none — event renamed or removed)"
          }. Update arcSubscriber.ts to match, then re-run.`,
      );
    }
  }
}
